# Generated by Django 5.2.1 on 2025-05-31 18:31

from django.db import migrations

def populate_status(apps, schemaeditor):
    entries = {
        "published": "A post visible to all users",
        "draft": "A post only the author can see",
        "archived": "An older post, only visible to logged in users"
    }
    Status = apps.get_model("posts", "Status")
    for key, value in entries.items():
        status_obj = Status(name=key, description=value)
        status_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_status_post_status'),
    ]

    operations = [
        migrations.RunPython(populate_status)
    ]
